-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 16:11:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema littlelemondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema littlelemondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `littlelemondb` DEFAULT CHARACTER SET utf8mb3 ;
USE `littlelemondb` ;

-- -----------------------------------------------------
-- Table `littlelemondb`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemondb`.`bookings` (
  `BookingID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `TableNumber` INT NOT NULL,
  PRIMARY KEY (`BookingID`),
  UNIQUE INDEX `BookingID_UNIQUE` (`BookingID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `littlelemondb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemondb`.`customers` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(225) NOT NULL,
  `PhoneNumber` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `bookings_BookingID` INT NOT NULL,
  PRIMARY KEY (`CustomerID`, `bookings_BookingID`),
  INDEX `fk_customers_bookings1_idx` (`bookings_BookingID` ASC) VISIBLE,
  CONSTRAINT `fk_customers_bookings1`
    FOREIGN KEY (`bookings_BookingID`)
    REFERENCES `littlelemondb`.`bookings` (`BookingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 108
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `littlelemondb`.`order_delivery_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemondb`.`order_delivery_status` (
  `DeliveryID` INT NOT NULL AUTO_INCREMENT,
  `DeliveryDate` DATE NOT NULL,
  `DeliveryStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DeliveryID`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `littlelemondb`.`staff_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemondb`.`staff_info` (
  `StaffID` INT NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(45) NOT NULL,
  `Salary` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`StaffID`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `littlelemondb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemondb`.`orders` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `OrderDate` DATE NOT NULL,
  `Quantity` INT NOT NULL,
  `TotalCost` DECIMAL(10,0) NOT NULL,
  `customers_CustomerID` INT NOT NULL,
  `order_delivery_status_DeliveryID` INT NOT NULL,
  `staff_info_StaffID` INT NOT NULL,
  PRIMARY KEY (`OrderID`, `customers_CustomerID`, `staff_info_StaffID`),
  UNIQUE INDEX `OrderID_UNIQUE` (`OrderID` ASC) VISIBLE,
  INDEX `fk_orders_customers_idx` (`customers_CustomerID` ASC) VISIBLE,
  INDEX `fk_orders_order_delivery_status1_idx` (`order_delivery_status_DeliveryID` ASC) VISIBLE,
  INDEX `fk_orders_staff_info1_idx` (`staff_info_StaffID` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customers_CustomerID`)
    REFERENCES `littlelemondb`.`customers` (`CustomerID`),
  CONSTRAINT `fk_orders_order_delivery_status1`
    FOREIGN KEY (`order_delivery_status_DeliveryID`)
    REFERENCES `littlelemondb`.`order_delivery_status` (`DeliveryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_staff_info1`
    FOREIGN KEY (`staff_info_StaffID`)
    REFERENCES `littlelemondb`.`staff_info` (`StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `littlelemondb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemondb`.`menu` (
  `MenuID` INT NOT NULL,
  `Cuisine` VARCHAR(45) NOT NULL,
  `Starter` VARCHAR(45) NOT NULL,
  `Courses` VARCHAR(45) NOT NULL,
  `Drinks` VARCHAR(45) NOT NULL,
  `orders_OrderID` INT NOT NULL,
  `orders_customers_CustomerID` INT NOT NULL,
  PRIMARY KEY (`MenuID`, `orders_OrderID`, `orders_customers_CustomerID`),
  INDEX `fk_menu_orders1_idx` (`orders_OrderID` ASC, `orders_customers_CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_menu_orders1`
    FOREIGN KEY (`orders_OrderID` , `orders_customers_CustomerID`)
    REFERENCES `littlelemondb`.`orders` (`OrderID` , `customers_CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `littlelemondb`.`menuitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `littlelemondb`.`menuitems` (
  `MenuItemsID` INT NOT NULL AUTO_INCREMENT,
  `CourseName` VARCHAR(45) NOT NULL,
  `StarterName` VARCHAR(45) NOT NULL,
  `DessertName` VARCHAR(45) NOT NULL,
  `menu_MenuID` INT NOT NULL,
  `menu_orders_OrderID` INT NOT NULL,
  `menu_orders_customers_CustomerID` INT NOT NULL,
  PRIMARY KEY (`MenuItemsID`, `menu_MenuID`, `menu_orders_OrderID`, `menu_orders_customers_CustomerID`),
  INDEX `fk_menuitems_menu1_idx` (`menu_MenuID` ASC, `menu_orders_OrderID` ASC, `menu_orders_customers_CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_menuitems_menu1`
    FOREIGN KEY (`menu_MenuID` , `menu_orders_OrderID` , `menu_orders_customers_CustomerID`)
    REFERENCES `littlelemondb`.`menu` (`MenuID` , `orders_OrderID` , `orders_customers_CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
